app-modules:
    - oroinventory/js/app/modules/validator-constraints-module
dynamic-imports:
    oroform-validate:
        - oroinventory/js/validator/decimals-number
    oroinventory:
        - oroinventory/js/app/views/quantity-editor-view
        - oroinventory/js/datagrid/builder/inventory-status-builder
        - oroinventory/js/datagrid/builder/level-quantity-builder
