oro_payment_callback:
    resource:     "@OroPaymentBundle/Controller/Frontend/CallbackController.php"
    type:         annotation
    prefix:       /payment/callback
    options:
        frontend: true

oro_payment_methods_configs_rule:
    resource:     "@OroPaymentBundle/Controller/PaymentMethodsConfigsRuleController.php"
    type:         annotation
    prefix:       /paymentrule


#
# DEPRECATED OLD REST API ROUTES
#

oro_api_coptions_paymentmethodsconfigsrules:
    path: '/api/rest/{version}/paymentmethodsconfigsrules.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\PaymentBundle\Controller\Api\Rest\PaymentMethodsConfigsRuleController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1

oro_api_options_paymentmethodsconfigsrules:
    path: '/api/rest/{version}/paymentmethodsconfigsrules.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\PaymentBundle\Controller\Api\Rest\PaymentMethodsConfigsRuleController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1


#
# OLD REST API ROUTES
#

oro_api_enable_paymentmethodsconfigsrules:
    path: '/api/rest/{version}/paymentrules/{id}/enable.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\PaymentBundle\Controller\Api\Rest\PaymentMethodsConfigsRuleController::enableAction'
        version: latest
        _format: json
    requirements:
        version: latest|v1
        id: \d+
        _format: json

oro_api_disable_paymentmethodsconfigsrules:
    path: '/api/rest/{version}/paymentrules/{id}/disable.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\PaymentBundle\Controller\Api\Rest\PaymentMethodsConfigsRuleController::disableAction'
        version: latest
        _format: json
    requirements:
        version: latest|v1
        id: \d+
        _format: json
