layout:
    imports:
        -
            id: oro_product_grid_sidebar_filters
            root: page_sidebar
            namespace: product

    actions:
        - '@setOption':
            id: product_datagrid
            optionName: grid_render_parameters.extra_jsmodules
            optionValue: '=data["system_config_provider"].getValue("oro_product.filters_position") === "sidebar" ? ["oroproduct/js/app/datagrid/grid-sidebar-filters-builder"] : []'
