app-modules:
    - oroshoppinglist/js/app/modules/validator-constraints-module
dynamic-imports:
    oroform-validate:
        - oroshoppinglist/js/validator/decimal-precision
    oroshoppinglist:
        - oroshoppinglist/js/app/components/add-product-component
